### ISSUE TITLE
Issue during launch of mobile app. App is getting hang.

### ISSUE THREAD

**Issue by doramitrasekhar** [mparticle-integrations/mparticle-android-integration-apptentive#15]
Hi Team,

We are finding lag in our application when we launch the application, as observed from the logs.

1582891656.871 30951-31247/com.mcdonalds.app.qa W/SQLiteConnectionPool: The connection pool for database '+data+user+0+com.mitra_something+databases+mparticle_db' has been unable to grant a connection to thread 52312 (mParticleMessageHandler) with flags 0x2 for 4.0 seconds.

Requesting you to help us fix this issue soon.

**Comment by doramitrasekhar** [comment]
Waiting for response.

**Comment by samdozor** [comment]
Hi @doramitrasekhar thanks for the issue. This is the Apptentive kit repo - did you mean to log this issue here/do you have reason to think it's related to Apptentive?

**Comment by samdozor** [comment]
Also @doramitrasekhar can you please share your mParticle SDK version?

**Comment by doramitrasekhar** [comment]
makes sense.. we should log this issue in mParticle repo when we integrate it with apptentive-kit.
